/* eslint-disable react/no-unescaped-entities */
import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/styles.module.scss'
import SelectionItem from '../components/selection-items'
import widgets from '../widgets/styles.module.scss'

export default function Home() {
  const [loading, setLoading] = useState<boolean>(false)
  const [game, setGame] = useState<number>()
  const [selection, setSelection] = useState<string>("rock")
  const [opponent, setOpponent] = useState<number>(1)
  const [items, setItems] = useState<any[]>([])

  const uploadFields = (value: number) => {
      setLoading(true)
      fetch("https://codechallenge.boohma.com/play", {
          method: "post",
          headers: {
              "Content-Type": "application/json"
          },
          body: JSON.stringify({
            player: value
          })
      }).then(res => res.json())
          .then(data => {
              if(data.error){
                  alert(data.error)
                  setLoading(false)
              }
              else {
                setOpponent(data.computer)
                alert(data.results)
                setLoading(false)
              }
          })
          .catch(err => {
              setLoading(false)
              console.log(err)
          })
  }

  useEffect(() => {
    fetch(`https://codechallenge.boohma.com/choices`)
      .then((res) => res.json())
      .then((result) => {
        setItems(result);
      });
  }, []);

  console.log(items)
  
  const opponentSelection = () => {
    if (opponent === 1) {
      return (
        <span
          className={game
            ? `${styles.actions_item} ${styles.actions_item_left} ${styles.actions_item_left_active}`
            : `${styles.actions_item} ${styles.actions_item_left}`
          }
        >
          <Image src="/icons/rock.svg" alt="rock" width={200} height={200} />
          <br />
          <span className={`font-1 fs-35 ${styles.actions_text}`}>ROCK</span>
        </span>
      )
    } else if(opponent === 2) {
      return (
        <span
          className={game
            ? `${styles.actions_item} ${styles.actions_item_left} ${styles.actions_item_left_active}`
            : `${styles.actions_item} ${styles.actions_item_left}`
          }
        >
          <Image src="/icons/paper.svg" alt="paper" width={200} height={200} />
          <br />
          <span className={`font-1 fs-35 ${styles.actions_text}`}>PAPER</span>
        </span>
      )
    } else if(opponent === 3) {
      return (
        <span
          className={game
            ? `${styles.actions_item} ${styles.actions_item_left} ${styles.actions_item_left_active}`
            : `${styles.actions_item} ${styles.actions_item_left}`
          }
        >
          <Image src="/icons/scissors.svg" alt="scissors" width={200} height={200} />
          <br />
          <span className={`font-1 fs-35 ${styles.actions_text}`}>SCISSORS</span>
        </span>
      )
    } else if(opponent === 4) {
      return (
        <span
          className={game
            ? `${styles.actions_item} ${styles.actions_item_left} ${styles.actions_item_left_active}`
            : `${styles.actions_item} ${styles.actions_item_left}`
          }
        >
          <Image src="/icons/lizard.svg" alt="lizard" width={200} height={200} />
          <br />
          <span className={`font-1 fs-35 ${styles.actions_text}`}>LIZARD</span>
        </span>
      )
    } else if(opponent === 5) {
      return (
        <span
          className={game
            ? `${styles.actions_item} ${styles.actions_item_left} ${styles.actions_item_left_active}`
            : `${styles.actions_item} ${styles.actions_item_left}`
          }
        >
          <Image src="/icons/spock.svg" alt="spock" width={200} height={200} />
          <br />
          <span className={`font-1 fs-35 ${styles.actions_text}`}>SPOCK</span>
        </span>
      )
    }
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>RPSLS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={game ? `${styles.selections} ${styles.selections_active}` : styles.selections}>
          <div className={styles.title}>
            Pick your poison!
          </div>
          <div>The other player is waiting. Let's see if you can win this!</div>
          <div className={styles.options}>
            {items.map(item => {
              return (
                <span
                  key={item?.id}
                  className={game === item?.id
                    ? `${styles.options_item_active} ${styles.options_item}`
                    : styles.options_item
                  }
                  onClick={() => {
                    setGame(item?.id)
                    setSelection(item?.name)
                    uploadFields(item?.id)
                  }}
                >
                  <Image src={`/icons/${item?.name}.svg`} alt={item?.name} width={50} height={50} />
                  <span className={styles.tooltip}>{item?.name}</span>
                </span>
              )
            })}
            <span
              className={game === 1
                ? `${styles.options_item_active} ${styles.options_item}`
                : styles.options_item
              }
              onClick={() => {
                setGame(1)
                setSelection("rock")
                uploadFields(1)
              }}
            >
              <Image src="/icons/rock.svg" alt="rock" width={50} height={50} />
              <span className={styles.tooltip}>ROCK</span>
            </span>
            <span 
              className={game === 2
                ? `${styles.options_item_active} ${styles.options_item}`
                : styles.options_item
              }
              onClick={() => {
                setGame(2)
                setSelection("paper")
                uploadFields(2)
              }}
            >
              <Image src="/icons/paper.svg" alt="paper" width={50} height={50} />
              <span className={styles.tooltip}>PAPER</span>
            </span>
            <span 
              className={game === 3
                ? `${styles.options_item_active} ${styles.options_item}`
                : styles.options_item
              }
              onClick={() => {
                setGame(3)
                setSelection("scissors")
                uploadFields(3)
              }}
            >
              <Image src="/icons/scissors.svg" alt="scissors" width={50} height={50} />
              <span className={styles.tooltip}>SCISSORS</span>
            </span>
            <span 
              className={game === 4
                ? `${styles.options_item_active} ${styles.options_item}`
                : styles.options_item
              }
              onClick={() => {
                setGame(4)
                setSelection("lizard")
                uploadFields(4)
              }}
            >
              <Image src="/icons/lizard.svg" alt="lizard" width={50} height={50} />
              <span className={styles.tooltip}>LIZARD</span>
            </span>
            <span 
              className={game === 5
                ? `${styles.options_item_active} ${styles.options_item}`
                : styles.options_item
              }
              onClick={() => {
                setGame(5)
                setSelection("spock")
                uploadFields(5)
              }}
            >
              <Image src="/icons/spock.svg" alt="spock" width={50} height={50} />
              <span className={styles.tooltip}>SPOCK</span>
            </span>
          </div>
        </div>
        <div className={styles.actions}>
          {/* <span 
            className={game
              ? `${styles.actions_item} ${styles.actions_item_left} ${styles.actions_item_left_active}`
              : `${styles.actions_item} ${styles.actions_item_left}`
            }
          >
            <Image src="/icons/scissors.svg" alt="scissors" width={200} height={200} />
            <br />
            <span className={`font-1 fs-35 ${styles.actions_text}`}>SCISSORS</span>
          </span> */}
          {opponentSelection()}
          <span className={game ? `${styles.vs} ${styles.vs_active}` : `${styles.vs}`}>
            <Image src="/icons/vs.svg" alt="scissors" width={50} height={50} />
          </span>
          <span
            className={game
              ? `${styles.actions_item} ${styles.actions_item_right} ${styles.actions_item_right_active}`
              : `${styles.actions_item} ${styles.actions_item_right}`
            }
          >
            <Image src={`/icons/${selection}.svg`} alt={selection} width={200} height={200} />
            <br />
            <span className={`font-1 fs-35 ${styles.actions_text}`}>{selection}</span>
          </span>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
